AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a S3 Bucket"
Parameters:
  AppName:
    Type: String
  Environment:
    Type: String

Resources:
  MyInputBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Join [ "-", [ !Ref AppName, "input", !Ref Environment ] ]

  MyOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ !Ref AppName, "output", !Ref Environment ] ]
