AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a S3 Bucket"
Parameters:
  AppName:
    Type: String
  Environment:
    Type: String
  Region:
    Type: String
  AccountID:
    Type: String
  QueueName:
    Type: String
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Join [ "-", [ !Ref AppName, !Ref Environment ] ]
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !Join [":", ["arn:aws:sqs", !Ref Region, !Ref Account, !Join ["-", [!Ref QueueName, !Ref Environment]]]]
            Filter:
              S3Key:
                Rules:
                  - Name: mp4-suffix
                    Value: .mp4
          - Event: s3:ObjectCreated:*
            Queue: !Join [":", ["arn:aws:sqs", !Ref Region, !Ref Account, !Join ["-", [!Ref QueueName, !Ref Environment]]]]
            Filter:
              S3Key:
                Rules:
                  - Name: mp3-suffix
                    Value: .mp3
          - Event: s3:ObjectCreated:*
            Queue: !Join [":", ["arn:aws:sqs", !Ref Region, !Ref Account, !Join ["-", [!Ref QueueName, !Ref Environment]]]]
            Filter:
              S3Key:
                Rules:
                  - Name: wav-suffix
                    Value: .wav
          - Event: s3:ObjectCreated:*
            Queue: !Join [":", ["arn:aws:sqs", !Ref Region, !Ref Account, !Join ["-", [!Ref QueueName, !Ref Environment]]]]
            Filter:
              S3Key:
                Rules:
                  - Name: flac-suffix
                    Value: .flac

            #!Join [":",["arn:aws:sqs",!Ref Region, !Ref AccountID, !Join ["-", [!Ref QueueName, !Ref Environment]]]]
            